### ISSUE TITLE
Compiler Errors with Build

### ISSUE THREAD

**Issue by crawfis** [ELowry/Unity_InputLayers_Documentation#2]
> **Unity Version:** 6000.0.19f1

## Build Errors

If you try to make a Build (at least for Windows) you will get compiler errors. The problem I believe is that your .asmdef files have dependencies on your other .asmdef files and these are not broken down into Editor scripts and Runtime scripts. You need separate files for those or need to wrap all Editor code with in #if UNITY_EDITOR/#endif blocks.

**Comment by ELowry** [comment]
Hi there!

Thanks for reporting this!
I haven't had errors when I last tried building, but that may have been luck; I'll try with a fresh project to see what happens.

I will try and get back to you as soon as possible with a fix.

**Comment by ELowry** [comment]
PS: The asset has been updated in [the asset store](https://assetstore.unity.com/packages/slug/259582).

**Comment by crawfis** [comment]
Great. Thanks. Hope to be able to look at it more closely next month.
